config/routes.rb
Rails.application.routes.draw do
  # topページ
  root 'homes#top'

  # 説明ページ
  get 'about' => 'homes#about'

  # ログイン機能
  devise_for :users, skip: :all
  devise_scope :user do
    get 'login' => 'devise/sessions#new', as: :new_user_session
    post 'login' => 'devise/sessions#create', as: :user_session
    delete 'logout' => 'devise/sessions#destroy', as: :destroy_user_session
    get 'signup' => 'devise/registrations#new', as: :new_user_registration
    post 'signup' => 'devise/registrations#create', as: :user_registration
    # ゲストログイン
    post 'guest_login' => 'users/sessions#guest'
  end

  # マイページ
  get 'mypage' => 'users#mypage'
  # get 'mypage/edit' => 'users#edit'
  get 'mypage/alert' => 'users#alert'
  patch 'withdraw' => 'users#withdraw'

  # プロフィール
  resources :profiles, param: :code do
    collection do
      # プロフィール検索
      get 'search' => 'profiles#search'
    end
    member do
      # 公開設定
      get 'status' => 'profiles#status'
      # 自己紹介コメント
      resources :comments, except: [:new, :index, :show, :edit]
      # リンク
      resources :links, except: [:show, :edit]
      # カラーテーマ
      resource :colors, only: [:edit, :update]
      # 機能設定
      resource :function_settings, only: [:edit, :update]
      # タイムライン
      resources :posts, path: 'timeline', except: [:new, :show, :edit]
      # カレンダー
      resources :schedules, except: [:new, :edit, :update] do
        collection do
          get :completed
        end
      end
      # ギャラリー
      resources :images, path: 'gallery', except: [:show] do
        collection do
          get :list
        end
      end
      # フォームメール
      resources :inquiries, path: 'mail', except: [:edit, :update, :show] do
        collection do
          post :confirm
          post :back
        end
      end
    end
  end

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :schedules, dependent: :destroy
  has_many :inquiries, dependent: :destroy
  has_many :links, dependent: :destroy
  has_one :color, dependent: :destroy
  has_many :images, dependent: :destroy
  has_one :function_setting, dependent: :destroy
  accepts_nested_attributes_for :function_setting

  # プロフィールコード、名前は空白禁止
  with_options presence: true do
    # プロフィールコードは一意で20文字以内、アクション名と被らないこと
    validates :code, uniqueness: true, length: { maximum: 20 }, format: { with: /\A[a-z0-9]+\z/ },
                     exclusion: { in: %w[new search] }
    # 名前は20文字以内
    validates :name, length: { maximum: 20 }
  end

  # 自己紹介は160文字以内
  validates :introduction, length: { maximum: 160 }

  # image_idに画像投稿機能を追加
  attachment :image

  # 公開設定をenum管理
  enum status: { "公開": 0, "非公開": 1 }

  # URLのIDをプロフィールコードに
  def to_param
    code
  end

  # ユーザー検索
  def self.search(keyword)
    where(['code like? OR name like?', "%#{keyword}%", "%#{keyword}%"]).where.not(status: :"非公開")
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  # show、search以外はログインユーザーのみ許可
  before_action :authenticate_user!, except: %i[show search]
  # 操作ユーザーの確認
  before_action :set_profile, only: %i[edit status update destroy]

  # プロフィールページ
  def show
    @profile = Profile.find_by(code: params[:code])
    @comment = Comment.new
    # 非公開プロフィールへのアクセスをブロック
    release_check(@profile)
  end

  # プロフィール作成フォーム
  def new
    @profile = Profile.new
    @profile.build_function_setting
  end

  # プロフィールを新規作成
  def create
    @profile = Profile.new(profile_params)
    if @profile.save
      @color = Color.create(profile_id: @profile.id)
      flash[:notice] = 'プロフィールを新規作成しました。'
      redirect_to mypage_path
    else
      render 'new'
    end
  end

  # プロフィール編集フォーム
  def edit; end

  # 公開設定編集ページ
  def status; end

  # プロフィールへの編集を保存
  def update
    if @profile.update(profile_params)
      flash[:notice] = 'プロフィールを編集しました。'
      redirect_to profile_path(@profile)
    else
      render 'edit'
    end
  end

  # プロフィール一覧(削除ページ)
  def index
    @profiles = current_user.profiles
  end

  # プロフィールを削除
  def destroy
    @profile.destroy
    flash[:notice] = 'プロフィールを削除しました。'
    redirect_to mypage_path
  end

  # ユーザー検索
  def search
    @profiles = Profile.search(params[:keyword])
    @keyword = params[:keyword]
  end

  private

  def profile_params
    params.require(:profile).permit(:code, :name, :image, :introduction, :status,
                                    function_setting_attributes: %i[id timeline schedule gallery mail]).merge(user_id: current_user.id)
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_header.html.erb
 <!--ログインしている場合-->
<% if user_signed_in? %>
  <nav>
    <div class="menu-ber">
      <!--ログインしている場合-->
      <% if user_signed_in? %>
      <ul class="nav justify-content-end align-items-end">
        <li class="nav-item">
          <%= link_to "マイページ", mypage_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
        <% end %>
        <!--プロフィールオーナーがログインしている場合-->
        <% if current_user_signed_in?(profile) %>
        <li class="nav-item">
          <div class="nav-link">
          <button class="menu-btn btn btn-outline-secondary frex justify-content-end">
            <i class="fas fa-cog"></i>
          </button>
          </div>
        </li>
        <% end %>
      </ul>
    </div>
    <!--プロフィールオーナーがログインしている場合-->
    <% if current_user_signed_in?(profile) %>

      <ul class="menu-nav nav flex-column">

        <h6 class="nav-item">
          <i class="fas fa-address-card"> Profile</i>
        </h6>
        <!--プロフィール編集ページへのリンク-->
        <li class="nav-item">
          <%= link_to edit_profile_path(profile), class: "nav-link" do %>
            <i class="fas fa-pen-nib"></i> 名前やコメントを編集する
          <% end %>
        </li>
        <!--機能の追加・削除ページへのリンク-->
        <li class="nav-item">
          <%= link_to edit_function_settings_path(profile), class: "nav-link" do %>
            <i class="fas fa-clipboard-list"></i> 機能の公開設定を変更する
          <% end %>
        </li>
        <!--公開・非公開設定ページへのリンク-->

        <li class="nav-item">
          <%= link_to status_profile_path(profile), class: "nav-link" do %>
            <% if profile.status == "公開" %>
              <i class="fas fa-lock-open"></i> 公開・非公開設定
            <% elsif profile.status == "非公開" %>
              <i class="fas fa-lock"></i> 公開・非公開設
            <% end %>
          <% end %>
        </li>

        <h6 class="nav-item">
          <i class="fas fa-link"> Link</i>
        </h6>
        <!--リンクの追加ページへのリンク-->
        <li class="nav-item">
          <%= link_to new_link_path(profile), class: "nav-link" do %>
            <i class="fas fa-plus"></i> リンクを追加する
          <% end %>
        </li>

        <!--リンクが存在した場合-->
        <% if profile.links.present? %>
          <!--リンク一覧画面へのリンク-->
          <li class="nav-item">
            <%= link_to links_path(profile), class: "nav-link" do %>
              <i class="fas fa-pen-nib"></i> リンクを編集する
            <% end %>
          </li>
        <% end %>

        <h6 class="nav-item">
          <i class="fas fa-palette"> Color</i>
        </h6>
        <!--カラーテーマ編集ページへのリンク-->
        <li class="nav-item">
          <%= link_to edit_colors_path(profile), class: "nav-link" do %>
            <i class="fas fa-paint-brush"></i> カラーテーマを変更する
          <% end %>
        </li>

        <h6 class="nav-item">
          <i class="fas fa-mail-bulk"> Mail</i>
        </h6>
        <!--メールボックスへのリンク-->
        <li class="nav-item">
          <%= link_to inquiries_path(profile), class: "nav-link" do %>
            <i class="fas fa-envelope-open-text"></i> 受信メールを確認する
          <% end %>
        </li>

      </ul>
    <% end %>
  </nav>
  <script>
    const menubtn = document.querySelector('.menu-btn');
    const menunav = document.querySelector('.menu-nav');
    menubtn.addEventListener('click', () => {
      menunav.classList.toggle('open-menu');
    });
  </script>
<% end %>

<header class="profile-header">

  <!--フラッシュメッセージの呼び出し-->
  <%= render "layouts/flash" %>

  <div class="row profile-box">
    <div class="left d-flex justify-content-end align-items-center">
      <div class="icon-wrap">
        <%= attachment_image_tag profile, :image, class: "icon", fallback: "cat.png" %>
      </div>
    </div>
    <div class="col right">

      <div class="ber d-flex">
        <h1 class="name mb-0 my-auto"><%= profile.name %></h1>
        <nav>
          <ul class="nav">
            <!--リンク-->
            <% profile.links.each do |link| %>
              <li class="nav-item">
                <%= link_to link.url, class: "nav-link", target: "_blank", rel: "noopener noreferrer" do %>
                  <i class="<%= icon(link.category) %>"></i>
                <% end %>
              </li>
            <% end %>
          </ul>
        </nav>
      </div>

      <p class="ml-3 mb-0">
        <%== user_text(profile.introduction) %>
      </p>
    </div>
  </div>
</header>

app/views/profiles/_index.html.erb
<% profiles.each do |profile| %>
  <!--カード-->
  <div class="card mb-3" style="background: <%= profile.color.background %>;">
    <%= link_to profile_path(profile.code) do %>
    <div class="row g-0">
      <div class="col-md-3">
        <div class="wrap mx-auto my-2">
          <%= attachment_image_tag profile, :image, class: "card-img-top ", fallback: "cat.png" %>
        </div>
      </div>

      <!--カードボディ-->
      <div class="card-body col-md-9">
        <h5 class="card-title" style="color: <%= profile.color.accent %>;"><%= profile.name %></h5>
        <p class="card-text" style="color: <%= profile.color.text %>;"><%= safe_join(profile.introduction.split("\n"), tag(:br)) %></p>
      </div>

    </div>
    <% end %>

    <!--プロフィールオーナーがログインしている場合-->
    <% if current_user_signed_in?(profile) %>
      <!--カードフッター-->
      <div class="card-footer nav p-0" style="background-color: <%= "#{profile.color.accent}" + "4D" %>;">
        <!--公開設定の表示-->
        <span class="nav-link text-muted small">
          <%= link_to status_profile_path(profile), class: "nav-link", style: "color: #{profile.color.text};" do %>
            <% if profile.status == "公開" %>
              <i class="fas fa-lock-open"></i> <%= profile.status %>
            <% elsif profile.status == "非公開" %>
              <i class="fas fa-lock"></i> <%= profile.status %>
            <% end %>
          <% end %>
        </span>
        <!--カラーテーマ編集ページへのリンク-->
        <%= link_to edit_colors_path(profile), class: "ml-auto nav-link", style: "color: #{profile.color.text};" do %>
          <i class="fas fa-palette"></i>
        <% end %>
        <!--メールボックスへのリンク-->
        <%= link_to inquiries_path(profile), class: "nav-link", style: "color: #{profile.color.text};" do %>
          <i class="fas fa-mail-bulk"></i>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/profiles/_search_form.html.erb
<div class="row">
  <div class="search-form form-inline pull-right mr-3 ml-auto">
    <%= form_with url: search_profiles_path, method: :get, local: true do |f| %>
      <%= f.text_field :keyword, value: keyword, placeholder: "\uf002 ユーザー検索", type: "search", class: "fa form-control form-control-sm" %>
      <% f.submit %>
    <% end %>
  </div>
</div>

app/views/profiles/_tab-menu.html.erb
<!--メニューが２つ以上ある場合はタブを表示-->
<% if tab_unnecessary?(profile.function_setting) %>

  <nav class="mb-3">
    <ul class="tabs-menu">

    <!--プロフィールページ-->
    <li class="tab-item">
      <%= link_to profile_path, class: "tab-link #{active_if('profiles')}" do %>
        <i class="fas fa-paperclip"></i>
      <% end %>
    </li>

    <!--タイムライン-->
    <% if profile.function_setting.timeline %>
      <li class="tab-item">
        <%= link_to posts_path(profile), class: "tab-link #{active_if('posts')}" do %>
          <i class="far fa-clock"></i>
        <% end %>
      </li>
    <% end %>

    <!--スケジュール-->
    <% if profile.function_setting.schedule %>
      <li class="tab-item">
        <%= link_to schedules_path(profile), class: "tab-link #{active_if('schedules')}" do %>
          <i class="far fa-calendar-alt"></i>
        <% end %>
      </li>
    <% end %>

    <!--ギャラリー-->
    <% if profile.function_setting.gallery %>
      <li class="tab-item">
        <%= link_to images_path(profile), class: "tab-link #{active_if('images')}" do %>
          <i class="fas fa-image"></i>
        <% end %>
      </li>
    <% end %>

    <!--メール-->
    <% if profile.function_setting.mail %>
      <li class="tab-item">
        <%= link_to new_inquiry_path(profile), class: "tab-link #{active_if('inquiries')}" do %>
          <i class="far fa-envelope"></i>
        <% end %>
      </li>
    <% end %>

    </ul>
  </nav>

<!--メニューがひとつのみの場合はタブを非表示-->
<% else %>

  <% nil %>

<% end %>

app/views/profiles/edit.html.erb
<div class="management-page">

  <!--ヘッダー呼び出し-->
  <%= render "layouts/header" %>
  <h2>プロフィール編集</h2>

  <!--プロフィール作成フォーム-->
  <div class="profile-form">
    <p><span class="small required"><i class="fas fa-asterisk"></i></span>は必須項目です。</p>

    <%= form_with model: @profile, local:true do |f| %>

      <!--エラーメッセージ-->
      <%= render "layouts/error", model: f.object %>

      <!--プロフィール-->
      <%= render "profiles/form/profile", { f: f, profile: @profile } %>

      <div class="form-group mb-3">
        <%= f.submit "確定", class: "btn btn-outline-success" %>
      </div>

    <% end %>
  </div>

  <!--フッター呼び出し-->
  <%= render "layouts/footer" %>

</div>

app/views/profiles/index.html.erb
<div class="management-page">

  <!--ヘッダー呼び出し-->
  <%= render "layouts/header" %>

  <!--プロフィール一覧-->
  <main class="mypage">
    <table class="table">
      <thead>
        <tr>
          <th>コード</th>
          <th>名前</th>
          <th>自己紹介</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @profiles.each do |profile| %>
        <tr>
          <th><%= profile.code %></th>
          <td><%= profile.name %></td>
          <td><%= profile.introduction.truncate(30) %></td>
          <td><%= link_to "削除", profile_path(profile.code), method: :delete, "data-confirm" => "削除すると元に戻すことはできません。本当に削除しますか？" %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </main>

  <!--フッター呼び出し-->
  <%= render "layouts/footer" %>

</div>

app/views/profiles/new.html.erb
<div class="management-page">

  <!--ヘッダー呼び出し-->
  <%= render "layouts/header" %>
  <h2>プロフィール作成</h2>

  <!--プロフィール作成フォーム-->
  <div class="profile-form">
    <p><span class="small required"><i class="fas fa-asterisk"></i></span>は必須項目です。</p>

    <%= form_with model: @profile, local:true do |f| %>

      <!--エラーメッセージ-->
      <%= render "layouts/error", model: f.object %>

      <!--プロフィール-->
      <%= render "profiles/form/profile", { f: f, profile: @profile } %>

      <!--機能公開設定-->
      <%= render "profiles/form/function_setting", { f: f, profile: @profile } %>

      <!--公開設定-->
      <%= render "profiles/form/status", f: f %>

      <!--プロフィールコード-->
      <%= render "profiles/form/code", f: f %>

      <div class="form-group mb-3">
        <%= f.submit "確定", class: "btn btn-outline-success" %>
      </div>

    <% end %>
  </div>

  <!--フッター呼び出し-->
  <%= render "layouts/footer" %>

</div>

app/views/profiles/search.html.erb
<div class="management-page">

  <!--ヘッダー呼び出し-->
  <%= render "layouts/header" %>
  <!--検索窓-->
  <%= render "profiles/search_form", keyword: @keyword %>

  <main class="search">
    <h2>ユーザー検索</h2>

    <!--条件に合うプロフィールがある場合-->
    <% if @profiles.present? %>
      <!--検索結果一覧-->
      <%= render 'profiles/index', profiles: @profiles %>
    <!--条件に合うプロフィールがない場合 -->
    <% else %>
      <div>
        <p>条件に合うプロフィールは存在しません。</p>
      </div>
    <% end %>
  </main>

  <!--フッター呼び出し-->
  <%= render "layouts/footer" %>

</div>

app/views/profiles/show.html.erb
<!--プロフィールカラーの反映-->
<%= render "colors/style", profile: @profile %>

<div class="profile-page %>">
  <!--ヘッダー呼び出し-->
  <%= render "profiles/header", profile: @profile %>

  <!--タブメニュー-->
  <%= render "profiles/tab-menu", profile: @profile %>

  <!--自己紹介コメント一覧-->
  <%= render "comments/index", { profile: @profile, comment: @comment } %>
</div>

app/views/profiles/status.html.erb
<div class="management-page">

  <!--ヘッダー呼び出し-->
  <%= render "layouts/header" %>
  <h2>プロフィール公開・非公開設定</h2>

  <p><span class="small required"><i class="fas fa-asterisk"></i></span>は必須項目です。</p>

  <%= form_with model: @profile, local:true do |f| %>

    <!--エラーメッセージ-->
    <%= render "layouts/error", model: f.object %>

    <!--公開設定-->
    <%= render "profiles/form/status", f: f %>

    <div class="form-group mb-3">
      <%= f.submit "確定", class: "btn btn-outline-success" %>
    </div>

  <% end %>

  <!--フッター呼び出し-->
  <%= render "layouts/footer" %>

</div>

app/views/profiles/timeline.html.erb
<div class="profile">
  <!--ヘッダー呼び出し-->
  <%= render "profiles/header", profile: @profile %>

  <!--タブメニュー-->
  <nav>
    <ul class="nav nav-tabs nav-fill">
    <li class="nav-item">
      <%= link_to profile_path, class: "nav-link" do %>
        <i class="fas fa-paperclip"></i>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to timeline_profile_path(@profile.id), class: "nav-link active" do %>
        <i class="far fa-clock"></i>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to "", class: "nav-link" do %>
        <i class="far fa-calendar-alt"></i>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to "", class: "nav-link" do %>
        <i class="far fa-envelope"></i>
      <% end %>
    </li>
    </ul>
  </nav>
  <!--新規投稿ボタン-->
    <div class="nav-item">
      <%= link_to "", class: "", "data-toggle": "modal", "data-target": "#postModal" do %>
        <i class="fas fa-plus"></i>
      <% end %>
    </div>
    <!--新規投稿モーダルの立ち上げ-->
    <div class="modal fade" id="postModal" tabindex="-1" role="dialog" aria-hidden="true">
      <%= render "posts/new", { profile: @profile, post: @post } %>
    </div>

  <!--投稿がある場合-->
  <% if @profile.posts.present? %>
    <%= @profile.posts.each do |post| %>
      <%= post.text %>
      <%= post.created_at %>
      <%= post.updeted_at %>
    <% end %>

  <!-- 投稿がない場合 -->
  <% else %>
    <div>
      <p>投稿はありません。</p>
    </div>
  <% end %>
</div>