config/routes.rb
Rails.application.routes.draw do
  # topページ
  root 'homes#top'

  # 説明ページ
  get 'about' => 'homes#about'

  # ログイン機能
  devise_for :users, skip: :all
  devise_scope :user do
    get 'login' => 'devise/sessions#new', as: :new_user_session
    post 'login' => 'devise/sessions#create', as: :user_session
    delete 'logout' => 'devise/sessions#destroy', as: :destroy_user_session
    get 'signup' => 'devise/registrations#new', as: :new_user_registration
    post 'signup' => 'devise/registrations#create', as: :user_registration
    # ゲストログイン
    post 'guest_login' => 'users/sessions#guest'
  end

  # マイページ
  get 'mypage' => 'users#mypage'
  # get 'mypage/edit' => 'users#edit'
  get 'mypage/alert' => 'users#alert'
  patch 'withdraw' => 'users#withdraw'

  # プロフィール
  resources :profiles, param: :code do
    collection do
      # プロフィール検索
      get 'search' => 'profiles#search'
    end
    member do
      # 公開設定
      get 'status' => 'profiles#status'
      # 自己紹介コメント
      resources :comments, except: [:new, :index, :show, :edit]
      # リンク
      resources :links, except: [:show, :edit]
      # カラーテーマ
      resource :colors, only: [:edit, :update]
      # 機能設定
      resource :function_settings, only: [:edit, :update]
      # タイムライン
      resources :posts, path: 'timeline', except: [:new, :show, :edit]
      # カレンダー
      resources :schedules, except: [:new, :edit, :update] do
        collection do
          get :completed
        end
      end
      # ギャラリー
      resources :images, path: 'gallery', except: [:show] do
        collection do
          get :list
        end
      end
      # フォームメール
      resources :inquiries, path: 'mail', except: [:edit, :update, :show] do
        collection do
          post :confirm
          post :back
        end
      end
    end
  end

end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :profile

  # プロフィールID、タイトル、開始時刻は空白禁止
  with_options presence: true do
    validates :profile_id
    validates :title
    validates :start_date
    validates :end_date
  end

  # 未完了の予定一覧を取得
  def self.waiting_schedules
    where('end_date > ?', DateTime.now)
  end

  # 完了した予定一覧を取得
  def self.completed_schedules
    where('end_date < ?', DateTime.now)
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  # index、completed以外はログインユーザーのみ許可
  before_action :authenticate_user!, except: %i[index completed]
  # プロフィールの特定
  before_action :set_profile, except: %i[index completed]

  # 予定一覧ページ
  def index
    @profile = Profile.find_by(code: params[:code])
    @schedules = @profile.schedules
    @waiting_schedules = @schedules.waiting_schedules.page(params[:page]).per(10).reverse_order
    @schedule = Schedule.new
    # 非公開プロフィールへのアクセスをブロック
    release_check(@profile)
  end

  # 終了した予定一覧ページ
  def completed
    @profile = Profile.find_by(code: params[:code])
    @schedules = @profile.schedules
    @completed_schedules = @schedules.completed_schedules.page(params[:page]).per(10).reverse_order
    @schedule = Schedule.new
    # 非公開プロフィールへのアクセスをブロック
    release_check(@profile)
  end

  # 新規予定作成
  def create
    @schedule = Schedule.new(schedule_params)
    @schedule.profile_id = @profile.id
    if @schedule.save
      flash[:notice] = '予定を追加しました。'
      redirect_to schedules_path(params[:code])
    else
      flash[:error] = '予定の追加に失敗しました。'
      @schedules = @profile.schedules
      render 'index'
    end
  end

  # 予定削除
  def destroy
    @schedule = Schedule.find(params[:id])
    @profile = @schedule.profile
    @schedule.destroy
    flash[:notice] = '投稿を削除しました。'
    redirect_to schedules_path(@profile)
  end

  private

  def schedule_params
    params.require(:schedule).permit(:title, :body, :start_date, :end_date)
  end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<div class="modal-dialog">
  <div class="modal-content">

    <div class="modal-header">
      <h2 class="modal-title">予定を追加</h2>
      <!--閉じるボタン-->
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>

    <!--フォーム-->
    <%= form_with(model: [profile, schedule], url: schedules_path, local: true) do |f| %>
      <div class="modal-body text-left">
        <p><span class="small required"><i class="fas fa-asterisk"></i></span>は必須項目です。</p>
        <div class="mb-3">
          <%= f.label :title, "タイトル", class: "form-label" %>
          <span class="small required"><i class="fas fa-asterisk"></i></span>
          <%= f.text_field :title, autofocus: true, autocomplete: "タイトル", class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :start_date, "開始日時", class: "form-label" %>
          <span class="small required"><i class="fas fa-asterisk"></i></span>
          <%= f.datetime_field :start_date, autofocus: true, autocomplete: "XXXX-XX-XX", class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :end_date, "終了日時", class: "form-label" %>
          <span class="small required"><i class="fas fa-asterisk"></i></span>
          <%= f.datetime_field :end_date, autofocus: true, autocomplete: "XXXX-XX-XX", class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :body, "詳細", class: "form-label" %>
          <%= f.text_area :body, autofocus: true, class: "form-control" %>
        </div>
      </div>

      <div class="modal-footer">
        <div class="actions">
          <%= f.submit "投稿", class: "btn btn-outline-secondary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/schedules/completed.html.erb
<div class="profile-page <%= colortheme(@profile) %>">

  <!--ヘッダー呼び出し-->
  <%= render "profiles/header", profile: @profile %>

  <!--タブメニュー-->
  <!--プロフィールカラーの反映-->
<%= render "colors/style", profile: @profile %>

<%= render "profiles/tab-menu", profile: @profile %>

  <nav>
    <ul class="nav">
      <!--プロフィールオーナーがログインしている場合-->
      <% if current_user_signed_in?(@profile) %>
        <!--新規投稿ボタン-->
        <li class="nav-link">
          <%= link_to "#", class: "ml-3", "data-toggle": "modal", "data-target": "#scheduleModal" do %>
            <i class="fas fa-plus"></i>
          <% end %>
        </li>
        <!--新規投稿モーダルの立ち上げ-->
        <div id="scheduleModal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
          <%= render "schedules/form", { profile: @profile, schedule: @schedule } %>
        </div>
      <% end %>
      <!--予定へのリンク-->
      <li class="nav-link">
      <%= link_to schedules_path(@profile) do %>
        <i class="fas fa-history fa-flip-horizontal"></i> 予定を確認する
      <% end %>
      </li>
    </ul>
  </nav>

  <!--予定がある場合-->
  <% if @completed_schedules.present? %>

    <!--予定一覧-->
    <ul class="list-group list-group-flush list-group-flush">
    <% @completed_schedules.each do |schedule| %>
      <li class="list-group-item  d-flex justify-content-between align-items-center bg-transparent">
        <span>
          <small><%= "#{l schedule.start_date, format: :long}～#{l schedule.end_date, format: :long}" %></small>
          <br>
          <%= schedule.title %>
          <!--予定詳細に入力がある場合-->
          <% if schedule.body.present? %>
            <a class="and_more" data-toggle="collapse" href="#<%= "collapse" + schedule.id.to_s %>" role="button" aria-expanded="false" aria-controls="<%= "collapse" + schedule.id.to_s %>">
              <i class="fas fa-caret-down"></i>
            </a>
          <% end %>
        </span>
        <!--プロフィールオーナーがログインしている場合-->
        <% if current_user_signed_in?(@profile) %>
          <!--削除ボタン-->
          <%= link_to schedule_path(@profile, schedule), method: :delete, "data-confirm" => "投稿を削除しますか？" do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
        <% end %>
      </li>
      <div class="collapse mt-1" id="<%= "collapse" + schedule.id.to_s %>">
        <div class="card card-body">
          <%== user_text(schedule.body) %>
        </div>
      </div>
    <% end %>
    </ul>

    <!--ページネーション-->
    <div class="mt-3 d-flex justify-content-center">
      <%= paginate @completed_schedules %>
    </div>

  <!-- 予定がない場合 -->
  <% else %>
    <div>
      <p>終了した予定はありません。</p>
    </div>
  <% end %>

</div>

app/views/schedules/index.html.erb
<!--プロフィールカラーの反映-->
<%= render "colors/style", profile: @profile %>

<div class="profile-page <%= colortheme(@profile) %>">

  <!--ヘッダー呼び出し-->
  <%= render "profiles/header", profile: @profile %>

  <!--タブメニュー-->
  <%= render "profiles/tab-menu", profile: @profile %>

  <div class="row">
    <section class="col-md-7">

    <ul class="nav">
      <!--プロフィールオーナーがログインしている場合-->
      <% if current_user_signed_in?(@profile) %>
        <!--新規投稿ボタン-->
        <li class="nav-link">
          <%= link_to "#", class: "ml-3", "data-toggle": "modal", "data-target": "#scheduleModal" do %>
            <i class="fas fa-plus"></i> 予定を追加する
          <% end %>
        </li>
        <!--新規投稿モーダルの立ち上げ-->
        <div id="scheduleModal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
          <%= render "schedules/form", { profile: @profile, schedule: @schedule } %>
        </div>
      <% end %>
      <!--終了した予定へのリンク-->
      <li class="nav-link">
      <%= link_to completed_schedules_path(@profile) do %>
        <i class="fas fa-history"></i> 過去の予定を確認する
      <% end %>
      </li>
    </ul>

      <!--予定がある場合-->
      <% if @waiting_schedules.present? %>

        <!--予定一覧-->
        <ul class="list-group list-group-flush list-group-flush">
        <% @waiting_schedules.each do |schedule| %>
          <li class="list-group-item  d-flex justify-content-between align-items-center bg-transparent">
            <span>
              <small><%= "#{l schedule.start_date, format: :long}～#{l schedule.end_date, format: :long}" %></small>
              <br>
              <%= schedule.title %>
              <!--予定詳細に入力がある場合-->
              <% if schedule.body.present? %>
                <a class="and_more" data-toggle="collapse" href="#<%= "collapse" + schedule.id.to_s %>" role="button" aria-expanded="false" aria-controls="<%= "collapse" + schedule.id.to_s %>">
                  <i class="fas fa-caret-down"></i>
                </a>
              <% end %>
            </span>
            <!--プロフィールオーナーがログインしている場合-->
            <% if current_user_signed_in?(@profile) %>
              <!--削除ボタン-->
              <%= link_to schedule_path(@profile, schedule), method: :delete, "data-confirm" => "投稿を削除しますか？" do %>
                <i class="fas fa-trash-alt"></i>
              <% end %>
            <% end %>
          </li>
          <div class="collapse mt-1" id="<%= "collapse" + schedule.id.to_s %>">
            <div class="card bg-transparent card-body">
              <%== user_text(schedule.body) %>
            </div>
          </div>
        <% end %>
        </ul>

        <!--ページネーション-->
        <div class="mt-3 d-flex justify-content-center">
          <%= paginate @waiting_schedules %>
        </div>

      <!-- 予定がない場合 -->
      <% else %>
        <div>
          <p>予定の投稿がありません。</p>
        </div>
      <% end %>

    </section>
    <section class="col-md-5">
      <!--カレンダーの表示-->
      <div id="calendar"></div>
    </section>
  </div>

</div>