config/routes.rb
Rails.application.routes.draw do
  # topページ
  root 'homes#top'

  # 説明ページ
  get 'about' => 'homes#about'

  # ログイン機能
  devise_for :users, skip: :all
  devise_scope :user do
    get 'login' => 'devise/sessions#new', as: :new_user_session
    post 'login' => 'devise/sessions#create', as: :user_session
    delete 'logout' => 'devise/sessions#destroy', as: :destroy_user_session
    get 'signup' => 'devise/registrations#new', as: :new_user_registration
    post 'signup' => 'devise/registrations#create', as: :user_registration
    # ゲストログイン
    post 'guest_login' => 'users/sessions#guest'
  end

  # マイページ
  get 'mypage' => 'users#mypage'
  # get 'mypage/edit' => 'users#edit'
  get 'mypage/alert' => 'users#alert'
  patch 'withdraw' => 'users#withdraw'

  # プロフィール
  resources :profiles, param: :code do
    collection do
      # プロフィール検索
      get 'search' => 'profiles#search'
    end
    member do
      # 公開設定
      get 'status' => 'profiles#status'
      # 自己紹介コメント
      resources :comments, except: [:new, :index, :show, :edit]
      # リンク
      resources :links, except: [:show, :edit]
      # カラーテーマ
      resource :colors, only: [:edit, :update]
      # 機能設定
      resource :function_settings, only: [:edit, :update]
      # タイムライン
      resources :posts, path: 'timeline', except: [:new, :show, :edit]
      # カレンダー
      resources :schedules, except: [:new, :edit, :update] do
        collection do
          get :completed
        end
      end
      # ギャラリー
      resources :images, path: 'gallery', except: [:show] do
        collection do
          get :list
        end
      end
      # フォームメール
      resources :inquiries, path: 'mail', except: [:edit, :update, :show] do
        collection do
          post :confirm
          post :back
        end
      end
    end
  end

end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  belongs_to :profile

  # プロフィールID、名前、メールアドレス、投稿本文は空白禁止
  with_options presence: true do
    validates :profile_id
    validates :sender
    validates :email
    validates :message
  end
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  # index、show、destroyはログインユーザーのみ許可
  before_action :authenticate_user!, only: %i[index destroy]
  # プロフィールの特定
  before_action :set_profile, only: %i[index destroy]

  # フォームメール作成ページ
  def new
    @profile = Profile.find_by(code: params[:code])
    @inquiry = Inquiry.new
    # 非公開プロフィールへのアクセスをブロック
    release_check(@profile)
  end

  # 入力内容確認ページ
  def confirm
    @profile = Profile.find_by(code: params[:code])
    @inquiry = Inquiry.new(inquiry_params)
    @inquiry.profile_id = @profile.id
    # バリデーション確認
    render 'new' if @inquiry.invalid?
    # 非公開プロフィールへのアクセスをブロック
    release_check(@profile)
  end

  # 作成ページに戻る
  def back
    @profile = Profile.find_by(code: params[:code])
    @inquiry = Inquiry.new(inquiry_params)
    render 'new'
  end

  # メール保存・送信
  def create
    @profile = Profile.find_by(code: params[:code])
    @inquiry = Inquiry.new(inquiry_params)
    @inquiry.profile_id = @profile.id
    if @inquiry.save
      InquiryMailer.send_formmail(@profile, @inquiry).deliver_now
      flash[:notice] = 'メールを送信しました。'
      redirect_to new_inquiry_path(@profile)
    else
      flash[:error] = 'メールの送信に失敗しました。'
      render 'new'
    end
  end

  # メール一覧ページ
  def index
    @inquiries = @profile.inquiries.reverse_order
  end

  # メール削除
  def destroy
    @inquiry = Inquiry.find(params[:id])
    @inquiry.destroy
    flash[:notice] = 'メールを削除しました。'
    redirect_to inquiries_path(@profile)
  end

  private

  def inquiry_params
    params.require(:inquiry).permit(:sender, :email, :title, :message)
  end
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/views/inquiries/confirm.html.erb
<!--プロフィールカラーの反映-->
<%= render "colors/style", profile: @profile %>

<div class="profile-page <%= colortheme(@profile) %>">

  <!--ヘッダー呼び出し-->
  <%= render "profiles/header", profile: @profile %>

  <!--タブメニュー-->
  <%= render "profiles/tab-menu", profile: @profile %>

  <table class="table table-borderless">
    <tbody>
      <tr>
        <td colspan="2">
          下記内容で送信します。<br>
          ご確認のうえ、送信ボタンを押下してください。
        </td>
      </tr>
      <tr>
        <td class="text-center">名前</td>
        <td><%= @inquiry.sender %></td>
      </tr>
      <tr>
        <td class="text-center">メールアドレス</td>
        <td><%= @inquiry.email %></td>
      </tr>
          <tr>
        <td class="text-center">件名</td>
        <td><%= @inquiry.title %></td>
      </tr>
      <tr>
        <td class="text-center">メッセージ</td>
        <td style="white-space: pre-wrap;"><%= @inquiry.message %></td>
      </tr>
      <tr>
        <td>
          <div class="row justify-content-center">
            <div class="mr-3">
              <%= form_with(model: [@profile, @inquiry], url: inquiries_path, local: true) do |f| %>
                <%= f.hidden_field :sender %>
                <%= f.hidden_field :email %>
                <%= f.hidden_field :title %>
                <%= f.hidden_field :message %>
                <%= f.submit "送信", class: "btn btn-outline-success" %>
              <% end %>
            </div>
            <div class="">
              <%= form_with(model: [@profile, @inquiry], url: back_inquiries_path(@profile), local: true) do |f| %>
                <%= f.hidden_field :sender %>
                <%= f.hidden_field :email %>
                <%= f.hidden_field :title %>
                <%= f.hidden_field :message %>
                <%= f.submit "修正", class: "btn btn-outline-danger" %>
              <% end %>
            </div>
          </div>
        </td>
        </td>
      </tr>
    </tbody>
  </table>



</div>

app/views/inquiries/index.html.erb
<div class="management-page">

  <!--ヘッダー呼び出し-->
  <%= render "layouts/header" %>

  <main class="mypage">
    <h2>フォームメール受信履歴</h2>

    <!--フラッシュメッセージの呼び出し-->
    <%= render "layouts/flash" %>

    <!--受信メールがある場合-->
    <% if @inquiries.present? %>

      <table class="table">
        <thead>
          <tr>
            <th style="width: 15%">受信日時</th>
            <th style="width: 10%">送信者</th>
            <th style="width: 25%">メールアドレス</th>
            <th style="width: 45%">件名</th>
            <th style="width: 5%"></th>
          </tr>
        </thead>
        <tbody>
          <% @inquiries.each do |inquiry| %>
            <tr>
              <td><%= l inquiry.created_at, format: :long %></td>
              <td><%= inquiry.sender %></td>
              <td><%= inquiry.email %></td>
              <td>
                <%= inquiry.title %>
                <a class="and_more" data-toggle="collapse" href="#<%= "collapse" + inquiry.id.to_s %>" role="button" aria-expanded="false" aria-controls="<%= "collapse" + inquiry.id.to_s %>">
                    <i class="fas fa-caret-down"></i>
                </a>
              </td>
              <td>
                <!--削除ボタン-->
                <%= link_to inquiry_path(@profile, inquiry), method: :delete, "data-confirm" => "メールを削除しますか？" do %>
                  <i class="fas fa-trash-alt"></i>
                <% end %>
              </td>
            </tr>
            <tr class="collapse mt-1" id="<%= "collapse" + inquiry.id.to_s %>">
              <td colspan="5">
                <div class="card card-body">
                  <%== user_text(inquiry.message) %>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

    <!-- 受信メールがない場合 -->
    <% else %>
      <div>
        <p>メールは届いていません。</p>
      </div>
    <% end %>
  </main>

  <!--フッター呼び出し-->
  <%= render "layouts/footer" %>

</div>

app/views/inquiries/new.html.erb
<!--プロフィールカラーの反映-->
<%= render "colors/style", profile: @profile %>

<div class="profile-page <%= colortheme(@profile) %>">

  <!--ヘッダー呼び出し-->
  <%= render "profiles/header", profile: @profile %>

  <!--タブメニュー-->
  <%= render "profiles/tab-menu", profile: @profile %>

  <p>
    プロフィールオーナーへメールを送信できます。<br>
    <span class="small required"><i class="fas fa-asterisk"></i></span>は必須項目です。
  </p>

  <!--メール送信フォーム-->
  <%= form_with(model: [@profile, @inquiry], url: confirm_inquiries_path(@profile), local: true) do |f| %>

    <!--エラーメッセージ-->
    <%= render "layouts/error", model: f.object %>

    <div class="form-group mb-3">
      <%= f.label :sender, "名前" %>
      <span class="small required"><i class="fas fa-asterisk"></i></span>
      <%= f.text_field :sender, autofocus: true, class: "form-control" %>
    </div>

    <div class="form-group mb-3">
      <%= f.label :email, "メールアドレス" %>
      <span class="small required"><i class="fas fa-asterisk"></i></span>
      <%= f.email_field :email, class: "form-control" %>
    </div>

    <div class="form-group mb-3">
      <%= f.label :title, "件名" %>
      <%= f.text_field :title, class: "form-control" %>
    </div>

    <div class="form-grou mb-3">
      <%= f.label :message, "メッセージ" %>
      <span class="small required"><i class="fas fa-asterisk"></i></span>
      <%= f.text_area :message, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= f.submit '入力内容確認', class: "btn btn-outline-success" %>
    </div>
  <% end %>

</div>