config/routes.rb
Rails.application.routes.draw do
  # topページ
  root 'homes#top'

  # 説明ページ
  get 'about' => 'homes#about'

  # ログイン機能
  devise_for :users, skip: :all
  devise_scope :user do
    get 'login' => 'devise/sessions#new', as: :new_user_session
    post 'login' => 'devise/sessions#create', as: :user_session
    delete 'logout' => 'devise/sessions#destroy', as: :destroy_user_session
    get 'signup' => 'devise/registrations#new', as: :new_user_registration
    post 'signup' => 'devise/registrations#create', as: :user_registration
    # ゲストログイン
    post 'guest_login' => 'users/sessions#guest'
  end

  # マイページ
  get 'mypage' => 'users#mypage'
  # get 'mypage/edit' => 'users#edit'
  get 'mypage/alert' => 'users#alert'
  patch 'withdraw' => 'users#withdraw'

  # プロフィール
  resources :profiles, param: :code do
    collection do
      # プロフィール検索
      get 'search' => 'profiles#search'
    end
    member do
      # 公開設定
      get 'status' => 'profiles#status'
      # 自己紹介コメント
      resources :comments, except: [:new, :index, :show, :edit]
      # リンク
      resources :links, except: [:show, :edit]
      # カラーテーマ
      resource :colors, only: [:edit, :update]
      # 機能設定
      resource :function_settings, only: [:edit, :update]
      # タイムライン
      resources :posts, path: 'timeline', except: [:new, :show, :edit]
      # カレンダー
      resources :schedules, except: [:new, :edit, :update] do
        collection do
          get :completed
        end
      end
      # ギャラリー
      resources :images, path: 'gallery', except: [:show] do
        collection do
          get :list
        end
      end
      # フォームメール
      resources :inquiries, path: 'mail', except: [:edit, :update, :show] do
        collection do
          post :confirm
          post :back
        end
      end
    end
  end

end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :profile

  # プロフィールID、タイトルは空白禁止
  with_options presence: true do
    validates :profile_id
    validates :title
  end

  # body_idに画像投稿機能を追加
  attachment :body
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  # ログインユーザーのみ許可
  before_action :authenticate_user!, except: [:index]
  # プロフィールの特定
  before_action :set_profile, except: [:index]

  # ギャラリーページ
  def index
    @profile = Profile.find_by(code: params[:code])
    @images = @profile.images.page(params[:page]).per(20).reverse_order
    # 非公開プロフィールへのアクセスをブロック
    release_check(@profile)
  end

  # 新規投稿画面
  def new
    @image = Image.new
  end

  # 新規投稿
  def create
    @image = Image.new(image_params)
    @image.profile_id = @profile.id
    if @image.save
      flash[:notice] = '画像を追加しました。'
    else
      flash[:error] = '画像の追加に失敗しました。'
    end
    redirect_to images_path(@image.profile)
  end

  # 投稿一覧
  def list
    @images = @profile.images.page(params[:page]).per(20).reverse_order
  end

  # 投稿編集画面
  def edit
    @image = Image.find(params[:id])
    render 'edit'
  end

  # 投稿を編集
  def update
    @image = Image.find(params[:id])
    if @image.update(image_params)
      flash[:notice] = '画像を修正しました。'
    else
      flash[:error] = '画像の修正に失敗しました。'
    end
    redirect_to list_images_path(@profile)
  end

  # 投稿を削除
  def destroy
    @image = Image.find(params[:id])
    @profile = @image.profile
    @image.destroy
    flash[:notice] = '画像を削除しました。'
    redirect_to list_images_path(@profile)
  end

  private

  def image_params
    params.require(:image).permit(:body, :title)
  end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<p><span class="small required"><i class="fas fa-asterisk"></i></span>は必須項目です。</p>

<!--エラーメッセージ-->
<%= render "layouts/error", model: f.object %>

<div class="mb-3">
  <span>画像</span>
  <span class="small required mr-3"><i class="fas fa-asterisk"></i></span>
  <%= f.attachment_field :body %>
</div>

<div class="form-group mb-3">
  <%= f.label :title, "タイトル" %>
  <span class="small required mr-3"><i class="fas fa-asterisk"></i></span>
  <%= f.text_field :title, class: "form-control" %>
</div>

<div class="form-group mb-3">
  <%= f.submit "保存", class: "btn btn-outline-secondary" %>
</div>

app/views/images/edit.html.erb
<div class="management-page">

  <!--ヘッダー呼び出し-->
  <%= render "layouts/header" %>

  <h2>画像を編集</h2>

  <%= form_with(model: [@profile, @image], url: image_path(@profile, @image), local: true) do |f| %>
    <!--フォーム呼び出し-->
    <%= render "images/form", f: f %>
  <% end %>

  <!--フッター呼び出し-->
  <%= render "layouts/footer" %>

</div>

app/views/images/index.html.erb
<!--プロフィールカラーの反映-->
<%= render "colors/style", profile: @profile %>

<div class="profile-page <%= colortheme(@profile) %>">

  <!--ヘッダー呼び出し-->
  <%= render "profiles/header", profile: @profile %>

  <!--タブメニュー-->
  <%= render "profiles/tab-menu", profile: @profile %>

  <!--プロフィールオーナーがログインしている場合-->
  <% if current_user_signed_in?(@profile) %>
    <ul class="nav">
      <li class="nav-link">
        <!--新規投稿ボタン-->
        <%= link_to new_image_path do %>
          <i class="fas fa-plus"></i> 画像を投稿する
        <% end %>
      </li>
      <!--編集ボタン-->
      <li class="nav-link">
        <%= link_to list_images_path(@profile) do %>
          <i class="fas fa-pen-nib"></i> 画像を編集する
        <% end %>
      </li>
    </ul>
  <% end %>

  <!--投稿がある場合-->
  <% if @profile.images.present? %>
    <div class="image-list">
      <!--投稿一覧-->
      <% @images.each do |image| %>
        <div class="wrap">
          <%= link_to Refile.attachment_url(image, :body), "data-lightbox": image.body do %>
            <%= attachment_image_tag image, :body, fallback: "noimage.jpg" %>
          <% end %>
          <p class="title text-center">
            <%= image.title %><br>
            <small class="small"><%= l image.created_at, format: :default %></small>
          </p>
        </div>
      <% end %>
    </div>
    <!--ページネーション-->
    <div class="mt-3 d-flex justify-content-center">
      <%= paginate @images %>
    </div>

  <!-- 投稿がない場合 -->
  <% else %>
    <div>
      <p>投稿はありません。</p>
    </div>
  <% end %>

</div>
<!--Lightbox2の読み込み-->
<link href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/css/lightbox.css" rel="stylesheet">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/js/lightbox.min.js" type="text/javascript"></script>

app/views/images/list.html.erb
<div class="management-page">

  <!--ヘッダー呼び出し-->
  <%= render "layouts/header" %>

  <main class="mypage">

    <h2>画像一覧</h2>

    <!--投稿がある場合-->
    <% if @images.present? %>

      <table class="table align-middle">
        <thaed>
          <tr>
            <th style="width: 15%" class="text-center">画像</th>
            <th style="width: 55%">タイトル</th>
            <th style="width: 15%"></th>
            <th style="width: 15%"></th>
          </tr>
        </thaed>
        <tbody>
          <% @images.each do |image| %>
          <tr>
            <td class="align-middle text-center">
              <%= attachment_image_tag image, :body, class: "list-image" %>
            </td>
            <td class="align-middle">
              <%= image.title %>
            </td>
            <td class="align-middle text-center">
              <%= link_to "編集", edit_image_path(@profile, image) %>
            </td>
            <td class="align-middle text-center">
              <%= link_to "削除", image_path(@profile, image), method: :delete, "data-confirm" => "画像を削除しますか？" %>
            </td>
          </tr>
        </tbody>
        <% end %>
      </table>

    <!--投稿がない場合-->
    <% else %>
      <div>
        <p>投稿はありません。</p>
      </div>
    <% end %>

  </main>

  <!--フッター呼び出し-->
  <%= render "layouts/footer" %>

</div>

app/views/images/new.html.erb
<div class="management-page">

  <!--ヘッダー呼び出し-->
  <%= render "layouts/header" %>

  <h2>リンクを追加</h2>
  <p><span class="small required"><i class="fas fa-asterisk"></i></span>は必須項目です。</p>
  <!--フォーム-->
  <%= form_with(model: [@profile, @image], url: images_path, local: true) do |f| %>

    <!--エラーメッセージ-->
    <%= render "layouts/error", model: f.object %>

    <div class="mb-3">
      <span>画像</span>
      <span class="small required mr-3"><i class="fas fa-asterisk"></i></span>
      <%= f.attachment_field :body %>
    </div>

    <div class="form-group mb-3">
      <%= f.label :title, "タイトル" %>
      <span class="small required mr-3"><i class="fas fa-asterisk"></i></span>
      <%= f.text_field :title, class: "form-control" %>
    </div>

     <div class="form-group mb-3">
      <%= f.label :information, "説明" %>
      <%= f.text_area :information, class: "form-control" %>
    </div>

    <div class="form-group mb-3">
      <%= f.submit "保存", class: "btn btn-outline-secondary" %>
    </div>
  <% end %>

  <!--フッター呼び出し-->
  <%= render "layouts/footer" %>

</div>